version: '3.9'

services:
  postgres:
    image: postgres:18-alpine
    container_name: exercise_6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cestsecretchuuut
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - exercise6_data:/var/lib/postgresql/data
      - ./6-init.sql:/docker-entrypoint-initdb.d/6-init.sql

volumes:
  exercise6_data:
    driver: local
